### ISSUE TITLE
[#C6] 로그인 구현하기

### ISSUE THREAD

**Issue by NamKey** [f-lab-edu/yousinsa#8]
## 개요

- [x] Feature
- [ ] Bug Fix
- [ ] Setup

**Comment by maketheworldwise** [comment]
로그인 관련해서도 JWT 토큰 기반으로 진행할 것인지 세션 기반으로 진행할 것인지도 논의가 필요해보입니다!

**Comment by NamKey** [comment]
1차적으로 세션 기반으로 설계해서 단일 서버에서 동작하는 경우와 여러개의 서버로 동작하는 경우를 경험해보고
추후 기능 개선이나 변경으로 JWT로 변경하는거 어떠신가요?

**Comment by maketheworldwise** [comment]
좋습니다~ 세션 기반으로 진행하시죠!
